github_repositories:
  - name: platform-team-admin
    description: The Platform Engineer's Handbook - Repository to manage platform team membership and admin artifacts
    visibility: public
    branch_protection:
      - pattern: "main"
        enforce_admins: true
        require_signed_commits: true
    environments:
      - name: pulumi
      - name: pulumi-production
        reviewers:
          - Jdavid77

  - name: platform-core
    description: The Platform Engineer's Handbook - Core platform runtime
    visibility: public
    branch_protection:
      - pattern: "main"
        enforce_admins: true
        require_signed_commits: true
    environments:
      - name: platform-sandbox
        reviewers:
          - Jdavid77
      - name: app-dev
        reviewers:
          - Jdavid77
      - name: shared
        reviewers:
          - Jdavid77

  - name: platform-demo-app
    description: The Platform Engineer's Handbook - Demo application for testing the platform
    visibility: public
    branch_protection:
      - pattern: "main"
        enforce_admins: true
        # Semantic Release Bot will be used to commit files to this repository, so we need to disable for now
        # Thinking of an alternative approach to this, but for now, we will disable this requirement
        require_signed_commits: false
        required_pull_request_reviews:
          required_approving_review_count: 0
          dismiss_stale_reviews: false
          require_code_owner_reviews: false
          require_last_push_approval: false
          bypass_pull_request_allowances:
            apps:
              - github-actions
      - pattern: "*"
        enforce_admins: true
        require_signed_commits: true

  - name: platform-gitops
    description: The Platform Engineer's Handbook - FluxCD App-of-Apps Repository
    visibility: public
    branch_protection:
      - pattern: "main"
        enforce_admins: true
        require_signed_commits: true
        required_pull_request_reviews:
          required_approving_review_count: 0
          dismiss_stale_reviews: false
          require_code_owner_reviews: false
          require_last_push_approval: false
      - pattern: "*"
        enforce_admins: true
        require_signed_commits: true


  - name: platform-helm-chart
    description: The Platform Engineer's Handbook - Generic Helm Chart for Company-Wide Use
    visibility: public
    branch_protection:
      - pattern: "main"
        enforce_admins: true
        # Semantic Release again...
        require_signed_commits: false
        required_pull_request_reviews:
          required_approving_review_count: 0
          dismiss_stale_reviews: false
          require_code_owner_reviews: false
          require_last_push_approval: false
          bypass_pull_request_allowances:
            apps:
              - github-actions
      - pattern: "*"
        enforce_admins: true
        require_signed_commits: true

  - name: platform-services
    description: The Platform Engineer's Handbook - Platform Services Tenant Repository
    visibility: public
    branch_protection:
      - pattern: "main" # staging
        enforce_admins: true
        require_signed_commits: true
      - pattern: "production" # prod
        enforce_admins: true
        require_signed_commits: true
        required_pull_request_reviews:
          required_approving_review_count: 0
          dismiss_stale_reviews: false
          require_code_owner_reviews: false
          require_last_push_approval: false

github_organization_members:
  - name: Jdavid77
    github-role: admin
    github-username: Jdavid77
